# Once this file is changed, you'll need to trigger a Puppet run on the
# k8s workers (or whatever is running ocfweb) for the config to propagate to ocfweb.
---

force_lab_closed: false

# please remember: the banner is for urgent announcements!
# consider adding something to the website normally if it's not urgent or you
# plan to leave it there for a while.
banner_visible: true

banner_html: |
  <div class="update-banner" id="banner">
    <h4 id="banner-header"><b>Student Organizations Subdomain Migration</b></h4>
    <p>
      The university is migrating berkeley.edu subdomains for student organizations to studentorg.berkeley.edu.<br />
      See <a href="https://www.ocf.berkeley.edu/docs/services/vhost/subdomain-migration/">ocf.io/s/subdomain-migration</a> for the actions that your group will need to take.
    </p>
  </div>
  <style>
    #banner-header, #banner-header-2 {
      font-size: 125%;
    }
    #banner {
      display: block;
      color: black;
      font-size: 100%;
      background-color: #a8e3ff;
    }
    #banner:hover {
      background-color: #a8e3ff;
    }
  </style>
